esphome:
  name: bedroomscreen
  friendly_name: BedroomScreen

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Rh6RElbIOh/Iqiuw2t4TO8E7dlXbBG9DTNF91eACQZM="

ota:
  - platform: esphome
    password: "7511b1ea4cb44dfed95698a576727ecb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroomscreen Fallback Hotspot"
    password: "h9unZIlOBVQS"

captive_portal:

time:
  - platform: homeassistant
    id: ha_time

# define font to display words
font:
  - file: 'fonts/GothamRnd-Bold.ttf'
    id: GothamRndBold75
    size: 75
  - file: 'fonts/GothamRnd-Bold.ttf'
    id: GothamRndBold45
    size: 45
  - file: 'fonts/GothamRnd-Bold.ttf'
    id: GothamRndBold30
    size: 30
  - file: 'fonts/FiraSans-SemiBold.ttf'
    id: FiraSansSB25
    size: 25
  - file: 'fonts/FiraSans-Medium.ttf'
    id: FiraSansMed25
    size: 25
  - file: 'fonts/Literata-Bold.ttf'
    id: LiterataBold40
    size: 40
  - file: 'fonts/Literata-Medium.ttf'
    id: LiterataMedium25
    size: 28
  - file: 'fonts/Roboto-Medium.ttf'
    id: font_small
    size: 20
  - file: "gfonts://Roboto"
    id: font_medium
    size: 35
  - file: "gfonts://Roboto"
    id: font_large
    size: 35
  - file: 'fonts/Roboto-Medium.ttf'
    id: robot_medum20
    size: 23
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_70
    size: 100
    glyphs: [
      "󰖕", # Partly Cloudy
      "󰖙", # Sunny
      "󰖐", # Cloudy
      "󰖗", # Rainy
      "󰖘", # Snowy
      "󰖝", # Windy
      "󰣰", # Hollow Star
      ]
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_40
    size: 30
    glyphs: [
      "󱊦", # battery_high
      "󰗱", # EV charghing station
      "󰥕", # Clock!
      "󰁾", # Battery 50
      "󰭬", # Electric car
      "󰂄", # Battery charging
      "󱰻", # charge plug battery
      "󱧥", # Battery Clock
      "󰣰", # Map Distance
      "󰖝", # Windy
      "󰸃", # Temp High
      "󰸂", # Temp Low
      "󰖎", # Water Percent
    ]
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_41
    size: 40
    glyphs: [
      "󱊦", # battery_high
      "󰗱", # EV charghing station
      "󰥕", # Clock!
      "󰁾", # Battery 50
      "󰭬", # Electric car
      "󰂄", # Battery charging
      "󱰻", # charge plug battery
      "󱧥", # Battery Clock
      "󰣰", # Map Distance
      "󰖝", # Windy
      "󰸃", # Temp High
      "󰸂", # Temp Low
      "󰖎", # Water Percent
      "󱔚", # ev-plug-ccs2
      "󰉁", # Electric Flash
      "󱩘", # Electric Meter
      "󱌤", # Oil Tank Level
    ]
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: icon_font_85
    size: 75
    glyphs: [
      "󱊦", # battery_high
      "󰗱", # EV charghing station
      "󰥕", # Clock!
      "󰁾", # Battery 50
      "󰭬", # Electric car
      "󰂄", # Battery charging
      "󱰻", # charge plug battery
      "󱧥", # Battery Clock
      "󰣰", # Map Distance
      "󰖝", # Windy
      "󰸃", # Temp High
      "󰸂", # Temp Low
      "󰖎", # Water Percent
    ]

sensor:
  - platform: homeassistant
    name: "BMW Charging target"
    id: ix1_bmw_target
    entity_id: sensor.target_state_of_charge

  - platform: homeassistant
    name: "OCT Charging target"
    id: ix1_oct_target
    entity_id: number.octopus_energy_a_b50b9dad_intelligent_charge_target

  - platform: homeassistant
    name: "Remaining Battery"
    id: ix1_batt_percent
    entity_id: sensor.state_of_charge_last_known

  - platform: homeassistant
    name: "Remaining Range"
    id: ix1_batt_range
    entity_id: sensor.ix1_xdrive30_last_sent_remaining_range

  - platform: template
    name: "Distance (miles)"
    id: ix1_batt_range_mi
    unit_of_measurement: "mi"
    accuracy_decimals: 2
    update_interval: 60s
    lambda: |-
      if (id(ix1_batt_range).has_state()) {
        return id(ix1_batt_range).state * 0.621371;
      } else {
        return NAN;
      }
  - platform: homeassistant
    name: "Probability Rain"
    id: precipitation_probability
    entity_id: sensor.forecast_today_precipitation_probability

  - platform: homeassistant
    name: "High Temp"
    id: today_temperature
    entity_id: sensor.forecast_today_temperature

  - platform: homeassistant
    name: "Low Temp"
    id: low_temperature
    entity_id: sensor.forecast_today_low_temperature

  - platform: homeassistant
    name: "Wind"
    id: wind_speed
    entity_id: sensor.forecast_today_wind_speed

  - platform: homeassistant
    name: "Unit Cost"
    id: elec_cost
    entity_id: sensor.octopus_energy_electricity_22j0076936_1416962671002_current_rate



text_sensor:
  - platform: homeassistant
    entity_id: sensor.charging_status
    id: ix1_charging
    name: "Charging status"

  - platform: homeassistant
    name: "Charging Connector Status"
    entity_id: sensor.ix1_xdrive30_charging_connector_status
    id: ix1_chargeing_connector_status


  - platform: template
    name: "Formatted Charging Status"
    id: formatted_charging_status
    icon: mdi:ev-station
    update_interval: 60s
    lambda: |-
      if (id(ix1_charging).state == "NOCHARGING") {
        return {"Not Charging !"};
      } else if (id(ix1_charging).state == "CHARGINGPAUSED") {
        return {"Paused"};
      } else if (id(ix1_charging).state == "CHARGINGACTIVE") {
        return {"Active"};
      } else if (id(ix1_charging).state == "CHARGINGENDED") {
        return {"Finished"};
      } else {
        return {"Unknown"};
      }

  - platform: homeassistant
    entity_id: select.octopus_energy_a_b50b9dad_intelligent_target_time
    id: ix1_target_time
    name: "Target Time"

  - platform: homeassistant
    entity_id: sensor.octopus_energy_a_b50b9dad_intelligent_state
    id: ix1_int_state
    name: "Charging Plan"

  - platform: homeassistant
    entity_id: sensor.forecast_today_condition
    id: forecast_today_condition
    name: "Forecast Today"
  

  
# define SPI interface
spi:
  clk_pin: GPIO8
  mosi_pin: GPIO10

display:
  - platform: waveshare_epaper
    cs_pin: GPIO3
    dc_pin: GPIO5
    busy_pin: 
      number: GPIO4
      inverted: true
    reset_pin: GPIO2
    model: 7.50inv2p
    update_interval: 1min
    full_update_every: 720
    auto_clear_enabled: true
    lambda: |-
      it.strftime(20, 0, id(GothamRndBold45), TextAlign::TOP_LEFT, "%H:%M : %d/%m/%y         %A", id(ha_time).now());
      it.filled_rectangle(395, 0, 5, 480 );
      #
      if (id(forecast_today_condition).state == "partlycloudy") {
          it.printf(5, 115, id(icon_font_70), "󰖕");
          it.printf(20, 75, id(GothamRndBold30), "Weather Today: Partly Cloudy");
      } else if (id(forecast_today_condition).state == "cloudy") {
        it.printf(5,115, id(icon_font_70), "󰖐");
        it.printf(20, 75, id(GothamRndBold30), "Weather Today:  Cloudy");
      } else if (id(forecast_today_condition).state == "sunny") {
        it.printf(5, 115, id(icon_font_70), "󰖙");
        it.printf(20, 75, id(GothamRndBold30), "Weather Today:  Sunny");
      } else if (id(forecast_today_condition).state == "windy") {
        it.printf(5,115, id(icon_font_70), "󰖝");
        it.printf(20, 75, id(GothamRndBold30), "Weather Today:  Windy");
      } else if (id(forecast_today_condition).state == "rainy") {
        it.printf(5, 115, id(icon_font_70), "󰖗");
        it.printf(20, 75, id(GothamRndBold30), "Weather Today:  Rainy");
      } else if (id(forecast_today_condition).state == "cloudy") {
        it.printf(5, 115, id(icon_font_70), "󰖐");
        it.printf(20, 75, id(GothamRndBold30), "Weather Today:  Cloudy");
      }
      it.printf(110, 125, id(icon_font_40), "󰸃"); 
      it.printf(150, 125, id(GothamRndBold30), "%.1f°c", id(today_temperature).state);
      it.printf(110, 165, id(icon_font_40), "󰸂");
      it.printf(150, 165, id(GothamRndBold30), "%.1f°c", id(low_temperature).state); 
      it.printf(244, 125, id(icon_font_40), "󰖎");
      it.printf(280, 125, id(GothamRndBold30), "%.1f%%", id(precipitation_probability).state);
      it.printf(244, 165, id(icon_font_40), "󰖝");
      it.printf(280, 165, id(GothamRndBold30), "%.0fmph", id(wind_speed).state);
      #
      it.printf(50, 240, id(GothamRndBold30), "Unit Cost:%.2f £/kW", id(elec_cost).state);
      it.printf(10, 240, id(icon_font_41), "󰉁");
      it.printf(50, 290, id(GothamRndBold30), "Today Cost:%.2f £/kW", id(elec_cost).state);
      it.printf(10, 290, id(icon_font_41), "󱔚");
      it.printf(50, 330, id(GothamRndBold30), "Oil Tank:%.2f Full", id(elec_cost).state);
      it.printf(10, 330, id(icon_font_41), "󱔚");
      #
      it.printf(445, 80, id(GothamRndBold30), "iX1: %s", id(ix1_chargeing_connector_status).state.c_str());
      it.printf(405, 80, id(icon_font_41), "󱔚");
      #
      it.printf(405, 310, id(icon_font_85), "󰣰");
      it.printf(475, 310, id(GothamRndBold75), " %.1fmi", id(ix1_batt_range_mi).state);
      
      it.printf(405, 390, id(icon_font_85), "󰁾");
      it.printf(475, 390, id(GothamRndBold75), " %.1f%%", id(ix1_batt_percent).state);



      
